import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  zonaTopo: {
    paddingTop: 40,
    paddingBottom: 10,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  textoOla: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#2e7d32",
    marginBottom: 5,
  },
  textoAlertas: {
    fontSize: 16,
    color: "#555",
  },
  alertaDestaque: {
    fontWeight: "bold",
    color: "#9b111e",
  },
  zonaGrafico: {
    alignItems: "center",
    marginTop: 50,
  },
  graficoFundo: {
    backgroundColor: "#fff",
    borderRadius: 100,
    padding: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    justifyContent: "center",
    alignItems: "center",
    width: 160,
    height: 160,
  },
  logoCentro: {
    position: "absolute",
    objectFit: "contain",
    width: 90,
    height: 90,
    borderRadius: 45,
  },
  textoPercentagem: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginTop: 20,
    marginBottom: 55,
  },
  tabelasContainer: {
    flexDirection: "row",
    paddingHorizontal: 15,
    justifyContent: "space-between",
    paddingBottom: 40,
    marginTop: 15,
    height: 210,
  },
  colunaTabela: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 15,
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    paddingBottom: 15,
  },
  cabecalhoAmarelo: {
    backgroundColor: "#f0c609",
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    paddingVertical: 12,
    marginBottom: 10,
    textAlign: "center",
  },
  cabecalhoVermelho: {
    backgroundColor: "#9b111e",
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
    paddingVertical: 12,
    marginBottom: 10,
    textAlign: "center",
  },
  listaContainer: {
    paddingHorizontal: 10,
    maxHeight: 100,
  },
  itemLista: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 10,
    marginBottom: 8,
  },
  nomeItem: {
    fontSize: 14,
    color: "#333",
    flex: 1,
    marginRight: 6,
  },
  diasItem: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#777",
  },
  listaVazia: {
    textAlign: "center",
    color: "#aaa",
    fontStyle: "italic",
    marginTop: 10,
  },
});
