import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  fundoEscuro: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  cartaoModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "android" ? 60 : 40,
    minHeight: 400,
  },
  cabecalho: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  titulo: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  fotoContainer: {
    alignItems: "center",
    marginBottom: 5,
  },
  fotoPlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 12,
    backgroundColor: "#f1f3f5",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ddd",
    borderStyle: "dashed",
  },
  imagemProduto: {
    width: 90,
    height: 90,
    borderRadius: 12,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
    marginBottom: 5,
    marginTop: 10,
  },
  input: {
    backgroundColor: "#f1f3f5",
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    color: "#333",
    marginBottom: 5,
  },
  linhaLadoALado: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 5,
  },
  metadeEsq: {
    flex: 1,
    marginRight: 10,
  },
  metadeDir: {
    flex: 1,
    marginLeft: 10,
  },
  zonaQuantidade: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    marginBottom: 10,
  },
  botaoQtd: {
    backgroundColor: "#e9ecef",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  textoQtd: {
    fontSize: 18,
    fontWeight: "bold",
    marginHorizontal: 20,
    color: "#333",
  },
  botaoGuardar: {
    backgroundColor: "#2e7d32",
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 10,
  },
  rodapeBotoes: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  botaoMetade: {
    flex: 1,
  },
  botaoEliminar: {
    backgroundColor: "#f44336",
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
    marginRight: 10,
  },
  botaoGuardarMetade: {
    backgroundColor: "#2e7d32",
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: "center",
  },
  textoBotao: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
});
