import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  scroll: {
    flexGrow: 1,
    padding: 20,
  },
  botaoVoltar: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 30,
    marginBottom: 20,
  },
  textoBotaoVoltar: {
    color: "#2e7d32",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 10,
  },
  zonaTexto: {
    marginTop: 20,
    marginBottom: 25,
  },
  titulo: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#2e7d32",
  },
  cartaoDados: {
    backgroundColor: "#f8f9fa",
    borderRadius: 12,
    padding: 20,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: "#e9ecef",
  },
  labelDados: {
    fontSize: 13,
    color: "#888",
    fontWeight: "bold",
    textTransform: "uppercase",
    marginBottom: 5,
  },
  textoDados: {
    fontSize: 18,
    color: "#333",
    fontWeight: "600",
  },
  botaoAbrirModal: {
    backgroundColor: "#2e7d32",
    borderRadius: 10,
    height: 55,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 15,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  textoBotaoAbrirModal: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  botaoLogout: {
    backgroundColor: "#f44336",
    borderRadius: 10,
    height: 55,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  textoBotaoLogout: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  fundoEscuro: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
  },
  cartaoModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "android" ? 60 : 40,
  },
  cabecalhoModal: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  tituloModal: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  labelModal: {
    fontSize: 14,
    fontWeight: "600",
    color: "#555",
    marginBottom: 5,
  },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f1f3f5",
    borderRadius: 10,
    marginBottom: 15,
    paddingHorizontal: 15,
    height: 55,
    borderWidth: 1,
    borderColor: "transparent",
  },
  inputContainerErro: {
    borderColor: "#d32f2f",
    backgroundColor: "#fff5f5",
  },
  iconeInput: {
    marginRight: 10,
  },
  inputModal: {
    flex: 1,
    fontSize: 16,
    color: "#333",
  },
  iconeOlho: {
    padding: 5,
  },
  textoErro: {
    color: "#d32f2f",
    fontSize: 13,
    marginTop: -10,
    marginBottom: 15,
    marginLeft: 5,
  },
  botaoGuardar: {
    backgroundColor: "#2e7d32",
    borderRadius: 10,
    height: 55,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 5,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  textoBotaoGuardar: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
});
